### PR TITLE
Define a CMakeLists.txt file for each component and define better deps linking

### PR DESCRIPTION
**Pull request by ghost**
- Each component is defined with his own `CMakeLists.txt` file
- Each component is linked directly with his deps
- Some polishing

### CODE REVIEW

**Comment by jaytaph** [comment]
@steazzalini Thanks (as usual).. With larger commits, could you maybe squash the commits down into a single (or few) commits? This keeps the history a little bit more readable (i should do this too more often though :p)

**Comment by ghost** [comment]
`git squash` :confused:
I think is something I have to learn :smile: 
Good to know that you can do so btw!

**Comment by jaytaph** [comment]
It should be pretty doable with this explanation: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by ghost** [comment]
Close this in favour to #226

**Pull request closed without merging**
