### PR TITLE
Define a CMakeLists.txt file for each component

### PR DESCRIPTION
**Pull request by ghost**
- Each component is defined with his own `CMakeLists.txt` file
- Each component is linked directly with his deps
- Some polishing

### CODE REVIEW

**Comment by ghost** [comment]
The following graph represent how components are linked each other.
ATM each component is linked with all his dependency, direct and non direct.

For example:
- `command` `~>` `generic`
- `command` `~>` `fastcgi` `~>` `generic`

Should we link only direct deps to remove some noise and make it more clear?
And if so, what about circles?

_(In this graph 3rd party libs are not included.)_

deps

**Comment by jaytaph** [comment]
@steazzalini Thanks for the awesome work on setting this all up.. I'd gives a good insight in what's going on at the moment.

I think we can still change many things in the whole component setup. There should be no reason for the `commands` (or `fastcgi`, or `repl`) to have direct access to `objects` for instance. The whole "generic" should be a sublayer below vm, objects as well probably, and again not have any references to the "front components" (fastcgi, repl, command, maybe not even debugger, which is the dbgp debugger).

I guess for now it's a big work-in-progress to get everything sorted out. I'd reckon we should try and fix this asap, but since we started this project with no plan (and, still have no plan) i think still a lot can and will change..

**Comment by ghost** [comment]
I think some progress has been made :beers:
What do you think about it?  
I'm quite unsure about the `modules` component. I do not know too much about his domain and responsibility :confused:

No way to decouple `generic` and `debugger` :cry: 

deps

**Comment by jaytaph** [comment]
Thanks @steazzalini

**Pull request merged**
