### PR TITLE
Add OSX support

### PR DESCRIPTION
**Pull request by ghost**
Deps to install through `brew`:

``` shell
brew install icu4c fcgi flex bison
```

`bison` >= 2.7 is required due the usage of `%define api.pure` [here](https://github.com/saffire/saffire/blob/develop/src/components/compiler/saffire.y#L70)

OSX provieds `bison` 2.3 by default, so it must be upgraded.

I installed `bison` via `brew` and then hack the following:

``` shell
sudo mv /usr/bin/bison /usr/bin/bison
sudo ln /usr/local/Cellar/bison/3.0.4/bin/bison /usr/bin/bison
```

No tests ran.

### CODE REVIEW

**Comment by jaytaph** [comment]
`sudo mv /usr/bin/bison /usr/bin/bison`

need to move it to some other place `/usr/bin/bison.orig` or something?

**Comment by jaytaph** [comment]
It also needs

```
 brew install pkg-config pcre
```

**Comment by ghost** [comment]
Yeah sorry:

```
sudo mv /usr/bin/bison /usr/bin/bison23
```

Or something like that :)

**Comment by jaytaph** [comment]
@steazzalini 
The problem i'm currently facing is that I cannot compile anymore on a plain ubuntu system, as this runs on cmake 2.8.0.

Is it possible to have some kind of check to see if we can run the icu-module or not?

**Comment by ghost** [comment]
Could you explain a little bit more?
Is the cmake configuration that give you problems or the compilation?

PS: I notice that files generated files with bison and flex are stored into the src dir, not into the build dir. I haz to clean out these files manually to run a real clean build. That's another story but it's just a hint

**Comment by jaytaph** [comment]
> PS: I notice that files generated files with bison and flex are stored into the src dir, not into the build dir. I >haz to clean out these files manually to run a real clean build. That's another story but it's just a hint
> Yeah, everything that is generated should be generated into the build directory. That is not happening with a few files (but it would be easy enough to fix).

The OSX build works perfectly (except from some compiler warnings, which can be fixed), but with the same branch, I cannot compile on Ubuntu. I've checked, but it's actually that i'm running on an older ubuntu release (`Lucid 10.4 LTS`) which still uses CMake 2.8.0. Maybe that is not such a problem, we can not support that (or at least, not right now).

The vagrant machine that is supplied with saffire runs on trusty64, that seems to run ok.. 

I just check the branch on another (debian) machine, and if that runs correctly too, i can merge this one..

@steazzalini Maybe we need to change a bit of the installation documentation as well.. Not everything in there is valid anymore, and maybe have a bit of additional information. Also, we might need to do a check on CMake 2.8.3  (`cmake_minimum_required(VERSION 2.8.3)` ?)

**Comment by jaytaph** [comment]
Thanks @steazzalini

**Pull request merged**
