### PR TITLE
Move include dir to project root

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jaytaph** [comment]
There are still some include references to `/src/include` in the /unittest directory, so it seems.

**Comment by ghost** [comment]
Hey @jaytaph!
I cannot find these references. Could you give me some hints?

ps: I had some sync problems with the VM switching from branch to branch...

**Comment by jaytaph** [comment]
https://github.com/steazzalini/saffire/blob/527d6c988d224e15dbe36b06d7bf54899e7f742c/unittests/core/ini/ini.c#L7

These are actually cunit unittests (not saffire unittests). We've added some of them to make sure that we didn't break too much of the inner components (found in /src/general, mostly).

I don't think these tests are running now as well (they used to by running `make check`).. Maybe we could add this to the  `unittest.sh`, where we can run either `unittest.sh cunit`, `unittest.sh saffire` or by default, run all tests?

**Comment by ghost** [comment]
Now I understand. 
Found them and fixed :)
I'd like to suggest to build and run both of them by default, cunit core tests first probably.
Is it something to be done in this PR?

**Pull request merged**
